### PR TITLE
Fix Config Flow Issues

### PR DESCRIPTION
**Pull request by etmelvin**
Fixes gdgib/span#9

- Added the ability to provide your own access token instead of using proximity authentication
- Fixed an issue where config flow fails on user step when reauth is needed
- Fixed an issue where Home Assistant will discovery the same panel
- Fixed an issue where auth flow on discovery fails on missing access token

### CODE REVIEW

**Comment by jeffkibuule** [comment]
@gdgib Any chance we could get this merged soon? Would love to test it out.

**Review by gdgib — APPROVED** [review]

**Comment by gdgib** [comment]
Thanks for asking @jeffkibuule I apparently had a small email gap in github notifications there.  Didn't even see this until you asked.

Even bigger thanks to @etmelvin.  Nice work!

**Comment by gdgib** [comment]
@jeffkibuule let me know when you've tested this.  I kinda want to hold off on a release until one of us does, and I won't have time to test before the weekend.

**Comment by gdgib** [comment]
Hey @etmelvin nice work on this.  It's holding up very well so far in testing, and I appreciate the quality of the code.

**Comment by jeffkibuule** [comment]
Hmm, I'm glad I waited. While I don't have the authentication errors I usually get with HomeAssistant warning me, after a few days, each entity is listed as unavailable at about the same cadence as it previously told me Span wasn't working at all. :(

**Comment by etmelvin** [comment]
Is there a stack trace or some error logs you can provide?

**Comment by gdgib** [comment]
Also.... how many days (roughly) are we talking about here?

**Comment by jeffkibuule** [comment]
False alarm, it's been pretty durable for the last 2 weeks. Glad it got merged. Thank you!

**Pull request merged**
